### ISSUE TITLE
New updates break things on cedar-14

### ISSUE THREAD

**Issue by drewjoh** [fxtentacle/heroku-pdftk-buildpack#4]
The latest changes happened to break `pdftotext` for us with something around `libpoppler`.  Logging into console and trying to just use it manually resulted in:

```
./pdftotext: error while loading shared libraries: libpoppler.so.44: cannot open shared object file: No such file or directory
```

Not being an expert around this, I was ultimately able to resolve this by changing the buildpack URL we give to Heroku to reference the last commit before the changes.

```
https://github.com/fxtentacle/heroku-pdftk-buildpack.git#8b4c8da6a679b0499de668dbf1602fe0472be257
```

Hope this can help someone.  I really appreciate the work done here!  :)

**Comment by jayroh** [comment]
If I had to guess, it's because LD_LIBRARY_PATH is getting clobbered by the generated `pdftk.sh`

its contents are now

```sh
export LD_LIBRARY_PATH=:/app/bin
```

I'll have a PR for this sometime in the next few days because this same issue is happening to us with another buildpack -- can't load a shared object file because it's no longer in `LD_LIBRARY_PATH`

**Comment by jayroh** [comment]
@drewjoh I have a PR open with a fix for this but in the meantime you can use my fork at https://github.com/jayroh/heroku-pdftk-buildpack

**Comment by drewjoh** [comment]
Awesome, thanks @jayroh!

**Comment by eranrund** [comment]
Any plans to merge this?

**Comment by fxtentacle** [comment]
Did merge PR #5
